### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by haseebsaif** [mscdex/connect-busboy#25] opened 2022-02-28 11:54 UTC
`node_modules/busboy/lib/utils.js:465`
    `} catch {}`
      `      ^`

`SyntaxError: Unexpected token {`

from past week I am getting this error within the library.
any one else facing it?

Node V: `10.16.0`
NPM: `6.9.0`
lib version: Type definitions for connect-busboy 0.0
In package.json it saying `0.0.2`
also tried: `1.0.0`

**Comment by mscdex** [comment] 2022-02-28 13:03
Duplicate of https://github.com/mscdex/busboy/issues/288.

**Closed as completed by mscdex** 2022-02-28 13:03 UTC
Labels: duplicate
